export const ServiceType = {
    NEW_PATIENT_VISIT: "NEW_PATIENT_VISIT",
    FOLLOW_UP_VISIT: "FOLLOW_UP_VISIT",
    ANNUAL_PHYSICAL: "ANNUAL_PHYSICAL",
    URGENT_SAME_DAY: "URGENT_SAME_DAY",
    SICK_VISIT: "SICK_VISIT",
    VACCINATION: "VACCINATION",
    LAB_DRAW: "LAB_DRAW",
    PROCEDURE_MINOR: "PROCEDURE_MINOR",
    MEDICATION_REFILL: "MEDICATION_REFILL",
    TELEHEALTH_VISIT: "TELEHEALTH_VISIT",
} as const;

export type ServiceType = typeof ServiceType[keyof typeof ServiceType];